language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer install --prefer-dist --no-interaction

script: phpunit --configuration phpunit.xml --coverage-text

notifications:
  notifications:
    email:
      on_success: always
      on_failure: always